### ISSUE TITLE
The folder structure in the POD

### ISSUE THREAD

**Issue by luispc1998** [Arquisoft/viadeSpec#23]
This issue was requested by @labra to talk about the directory structure exposed in #21

As a summary of the related information in the pull request. We propose a viade/ folder in the root of the POD, here we should store the data related with the app. Inside it we will have other three folders: routes/, comments/, resources/. I believe that they are self-explanatory.

Why should we do it that way?

We could each of us (teams) have our own way to handle this, but supposing that one user used several of our apps, that would lead to a complex or even crazy structure of the user's POD data.

This is just a proposal that we consider pretty intuitive both for us and the user.

**Comment by Raulpemol** [comment]
Using this structure we will be able to handle shared routes exactly the same way as private ones. Using Solid permissions behind the sharing function of our applications, when reading the folder /routes, users will only see those routes which they have access to. Therefore, creating other folders for shared routes or a more complex structure to handle friends' routes is not needed.

**Comment by christianpe98** [comment]
Hi, I think there's actually already an issue to talk about this: #4

**Comment by luispc1998** [comment]
It's true, we are closing this issue, and posting everything there.
