### ISSUE TITLE
How to handle the GPX information when routes are represented as JSON-LD

### ISSUE THREAD

**Issue by luispc1998** [Arquisoft/viadeSpec#24]
The issue was requested by @labra to talk about the way of managing the gpx data in #21 

This topic was not really specified in the pull request, since we have focused in the POD storage. However we have studied the gpx standard and we have come to the following conclusions. Everything that it is commented here can be seen in the web of the schema of GPX 1.1
https://www.topografix.com/GPX/1/1/gpx.xsd

I'm providing here a simple example of a gpx: https://pastebin.com/Siq5xNv2

In this example we only have one trk, but we could have more than one according to the GPX specification. According to the schema, a trk is: "trk represents a track - an ordered list of points describing a path." This stands as what we should understand as a route. As it is commented in #21 we believe that we must join keeping the order of all the trkpt inside the trk and assign it to the variable viade:points of the JSON-LD. Note that trk can have name, description, etc. so we can directly check for that properties.

There are two types of nodes, "wpt" and "trkpt", as far as we could understand a Waypoint  (wpt) stands a remarkable point in the route, for instance "Catedral de Oviedo", whereas a Trackpoint (trkpt) would stand as a point the user passed through. 

Having said so, it could be interesting to add to #21 JSON-LD the waypoints, what do you think about that? Also, provided a gpx with several "trk", we believe that we should import each of them as different routes, do you agree?

**Comment by luispc1998** [comment]
Closed because there was already a relevant issue to cover this topic. I'm linking the proposal there instead, in order to continue de conversation.

**Comment by UO264345** [comment]
I'll answer both of your questions as reasonably as I can, taking that I still don't know much about the GPX standard:

- Although it can be interesting to have waypoints, I don't think they should be added to the spec. As it stands now in our application, we don't plan to provide a user with the possibility of attaching any info or files to a specific point in the route. Thus, I think they should be excluded from the JSON-LD-valid files; but if an application wants to use them, of course, they can use them, so it can be pondered to optionally add them.
- Yes, I believe each route should have its own independent file, so I fully agree on that point.
