### ISSUE TITLE
Proposal of es2a to add more things to en2a proposed spec

### ISSUE THREAD

**Issue by uo265363** [Arquisoft/viadeSpec#25]
- Adding "waypoints" as a list of points with latitude, longitude, name and description.
- Adding "author" with the webId of the route creator in the route jsonld file.
- Using json to store comments instead of txt, with content and date.

**Comment by Angelixus** [comment]
I think that the first 2 points could be optional attributes without any problem and I agree with the third point

**Comment by labra** [comment]
Could you change the title of the issue to something more descriptive avoiding the names of the teams? 

I would also probably separate the proposal into three different proposals.

**Comment by uo265363** [comment]
The issue is now splitted in 3 different issues.( #29 #28 #30 )
