### ISSUE TITLE
Add "waypoints" to the specification

### ISSUE THREAD

**Issue by uo265363** [Arquisoft/viadeSpec#28]
Adding "waypoints" optionally as a list of points with latitude, longitude, name and description.

**Comment by UO265308** [comment]
My team wants to follow the specification proposed for JSON-LD. We use the property "elevation" of the points of the route, so we'll be grateful if this feature is added to the standard.

As the points are @GeoCoordinates from schema.org, this property already exists and (I hope) it won't cause too much trouble.

I think that adding the following code to the @context will be enough:
```
"elevation": {
            "@id": "schema:elevation",
            "@type": "xs:decimal"
 }
```

**Comment by uo265363** [comment]
I think elevation should be added as an optional property instead of being a mandatory one, since it's redundant, google maps can get the elevation from the latitude and longitude.

**Comment by luispc1998** [comment]
I'll add them to the specification, elevation will appear in the examples. I'll take the schema.org property since it fits what we want, its type will xsd:double.
