### ISSUE TITLE
Specification suggestion for media file

### ISSUE THREAD

**Issue by csirgo** [Arquisoft/viadeSpec#32]
I am working on the upload of images and videos for a route and I've realized that the actual specification is not very practical.

As a user, I would find convenient to upload all the images and videos at once, not images first and then the videos. Well, if I do that I have to check the extension of each file to see if they are videos or images to create their respectives objects (in the spec they are Image and Video) and then add this objects to a common list.

I think this does make sense. If I want to separate the videos from the images when I show them, I would have to do an instance of or to check the extension to know what they are. Using instance of is always a bad idea and why would I check the extension of the files when I upload them if I have to check that again when I show them from de pod?

I suggest to have a unique class for Image and Video called Multimedia (for example), as both videos and images have the same attributes, and save them in two different lists: videos and images. In this way you don't have to check their type when you get them form the hasAnyMedia list.

PD: We could maintain both Video and Image if some people have already done this but I having two lists is mandatory.

**Comment by labra** [comment]
At this moment, I think the specification doesn't say anything about the media types. 

If you refer to this part: 

```
:Route {
  schema:name          xsd:string   ;
  . . .
  :hasMediaAttached    @:Image OR @:Video *;
}

:Image {
  schema:contentUrl   IRI ;
  schema:publishedDate xsd:datetime;
  schema:author     @:PodProfile;
}

:Video {
  schema:contentUrl   IRI;
  schema:publishedDate xsd:dateTime;
  schema:author     @:PodProfile;
}
```

It is only declaring the shapes of the RDF nodes that represent Images or videos, which in this case they use the same properties. 

For example, some RDF could be something like:

```
:oneRoute schema:name "Nice route" ;
 :hasMediaAttached :x1, :x2 .

:x1 schema:contentUrl <http://...x1.png>, schema:publishedDate "...",  schema:author :alice .
:x2 schema:contentUrl <http://...x2.mp4>, schema:publishedDate "...",  schema:author :bob .
```

And it would conform to the spec. 

In my opinion, that part was done at the beginning and it was mainly a draft which could probably be improved to add a `rdf:type` property. 

Possible values to declare media types can be found in schema.org. For example, [MediaObject](https://schema.org/MediaObject) could be used to specify that the type is a [`schema:MediaObject`](https://schema.org/MediaObject) or you could be more specific specifying that it is [`schema:ImageObject`](https://schema.org/ImageObject), [`schema:VideoObject`](https://schema.org/ImageObject) or even [`schema:AudioObject`](https://schema.org/AudioObject).

Notice that it is possible to declare inheritance relationships between those types, so both an ImageObject and VideoObject are also MediaObject's.

**Comment by csirgo** [comment]
I thought the first part of the spec referred the route item and the next part was the rdf because in the begining there was a recommendation about the route item. Thank you
