### ISSUE TITLE
Add "date" to the specification

### ISSUE THREAD

**Issue by PabloCanalSuarez** [Arquisoft/viadeSpec#35]
I think we should also add a "date" as optional in the route specification. Right now, in the last update, the specification recognizes date in comments, but taking this field into the route itself could be useful to represent the date in which it was done.

The date should be included in the context with something like:
```
"date": {
      "@id": "schema:Date",
      "@type": "xsd:date"
},
```

**Comment by uo265363** [comment]
I agree with adding date in routes, and i also think dates should be stored in milliseconds to avoid confusing date formats like dd-mm-yyyy, mm-dd-yyyy, etc.

**Comment by UO264345** [comment]
@uo265363 the date data type has defined its format as "YYYY-MM-DD", so there should be no problem with that. What I would suggest is using xsd:dateTime instead, to have also hours, minutes and seconds recorded.

**Comment by PabloCanalSuarez** [comment]
@uo265363 As our partner said, the format of the date shouln't be any problem as it's defined in a specific way. 

@UO264345 The `xsd:dateTime` format is okay with me as I've seen routes of major platforms (like Strava) store their routes with this format of time, so it could be useful to change it. Following this, the result would be something like:

```
"date": {
      "@id": "schema:DateTime",
      "@type": "xsd:dateTime"
},
```

**Comment by uo265363** [comment]
In that case we also prefer having xsd:dateTime in order to have the seconds included.

**Comment by PabloCanalSuarez** [comment]
Added to PR #21
