### ISSUE TITLE
Dealing with file permissions

### ISSUE THREAD

**Issue by InigoGutierrez** [Arquisoft/viadeSpec#37]
Finding a way to manage the permissions of files through code, either when creating files or changing existing files, is proving troublesome. Have you solved this problem and which would be a good approach to do it?

**Comment by jesQM** [comment]
We have finally solved it for our app, you may take a look at the issue of our repo regarding file sharing: https://github.com/Arquisoft/viade_en3a/issues/148

**Comment by InigoGutierrez** [comment]
Thank you very much! We actually think we solved this problem just today and using that same project, `solid-acl-utils`. What approach are you using to generate .acl files in order to manipulate them? Is the update of `solid-acl-utils` doing it for you? We solved it with another project, [solid-react-components](https://github.com/inrupt/solid-react-components), which has an ACL module allowing for the creation of .acl files for a specific resource with specific permissions. You might find it useful if you have problems with this.

**Comment by jesQM** [comment]
Oh, I will take a look at it, thanks.

> What approach are you using to generate .acl files in order to manipulate them?

Its done by the library with the 0.1.0 version. When accessing an .acl, if such file inherits parent's permissions, then the acl is not required, it will use the parent's and create a new acl from there, however, looks like at least one parent folder needs an acl (for example /viade in our case) else, some error may pop up.
